spring:
  application:
    name: meetzen-backend
  profiles:
    active: dev
  jackson:
    time-zone: UTC
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /v3/api-docs
  mvc:
    locale: en_US
    locale-resolver: fixed
